### ISSUE TITLE
Doesn't work with non-bundled entities

### ISSUE THREAD

**Issue by benjy** [webflo/inline_entity_form#9] opened 2015-03-10 14:14 UTC
Entities that don't have a bundle entity, such as user don't currently work.

**Comment by benjy** [comment] 2015-03-10 14:23
Can't reproduce this again today, was broken a few days ago. I'll test this week with some custom entities and report back.

**Comment by slashrsm** [comment] 2015-03-10 16:55
Duplicate of #10

**Closed as completed by slashrsm** 2015-03-10 16:55 UTC
